= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/exim-formula/compare/v0.7.0...v0.7.1++[0.7.1^] (2020-12-16)

=== Continuous Integration

* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/exim-formula/commit/b91a3b4cdc3266cf9ed5c748930538a75c473369[b91a3b4^])
* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/5ae076cf00f95c6bc2a751b3a1c2e92b86416380[5ae076c^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/f9b2d640481b1229a29d22dec280102b27f616c4[f9b2d64^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/bbf978cc291053fa0e2a7cde15e4316cd6b76de4[bbf978c^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/ec513498a0cc5d245cfa83a91f31a8de173795cc[ec51349^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/68b8e29ddd0f0a919aaca9f6a579c1ed4445498d[68b8e29^])

=== Styles

* *libtofs.jinja:* use Black-inspired Jinja formatting [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/4ef2119300ed14e6f4d1cefc62c7673ac125e47f[4ef2119^])

== link:++https://github.com/saltstack-formulas/exim-formula/compare/v0.6.1...v0.7.0++[0.7.0^] (2020-05-08)

=== Bug Fixes

* *libtofs:* “files_switch” mess up the variable exported by “map.jinja”
 [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/c7cbd5c773c155a64f25aa7d7298862a3c4ad494[c7cbd5c^])
* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/8356de82dc9aec66e25dd5a0a30f7ea933be3db7[8356de8^])

=== Continuous Integration

* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/bdb11961c18f61dc1d54880f12e7a5a89a58d50c[bdb1196^])
* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/7e1a0c19aaabc38539ddd819d0735228dc3b4506[7e1a0c1^])
* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/b40fa5fc387e6b79349082a76dbeda1bb3bbd044[b40fa5f^])
* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/c9fa91a656989de080d5b5b4156fcf74a3446d37[c9fa91a^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/edca1399abc9c8858b434f41a1a7909c946fa366[edca139^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/88b504b7b3318b0277637fdf95ac5d7d7eb180e9[88b504b^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/ef8968607a2007f33094712fbb206227513ff733[ef89686^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/00b5f307a3b71e3d8e983b522f85b46132472cb8[00b5f30^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/exim-formula/commit/bebca43d482282366ceed95410670d87e791135e[bebca43^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/00fc26f73ef9c1b50c6cb2bc19873e24dc9e248b[00fc26f^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/c2f403b881bda1f32583f3c24b37446688dffd46[c2f403b^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/7cb4790564f3a8856a1de49289bbddf1a7112896[7cb4790^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/29ab6b328e8fef16445157e488f149a512b29b7d[29ab6b3^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/5eb57e3700c820f7b0bb5125c5699c3b4ed413e0[5eb57e3^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/c07995c3cdf6717e166051684e39dcaa46d3a91f[c07995c^])

=== Documentation

* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/b0994c9112d0d2c332452d88e556a777dd7225e2[b0994c9^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/96b07dd6e75b0b486a3bc7fd14fd1dda06ce5b84[96b07dd^])

=== Features

* *config:* allow to manage config files under CONFDIR
(https://github.com/saltstack-formulas/exim-formula/commit/fd6debd529838eeb58bd954247cbd46b0d81254c[fd6debd^]),
closes https://github.com/saltstack-formulas/exim-formula/issues/17[#17]

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/b4a8f6a334600d8e4a4a4cf5756c213aacb3f87d[b4a8f6a^])

== link:++https://github.com/saltstack-formulas/exim-formula/compare/v0.6.0...v0.6.1++[0.6.1^] (2019-10-12)

=== Bug Fixes

* *rubocop:* add fixes using `rubocop --safe-auto-correct`
(https://github.com/saltstack-formulas/exim-formula/commit/d7ffc2c[d7ffc2c^])

=== Continuous Integration

* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/exim-formula/commit/efef553[efef553^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/exim-formula/commit/6030d81[6030d81^])
* *travis:* merge `rubocop` linter into main `lint` job
(https://github.com/saltstack-formulas/exim-formula/commit/5da375b[5da375b^])

== link:++https://github.com/saltstack-formulas/exim-formula/compare/v0.5.0...v0.6.0++[0.6.0^] (2019-10-08)

=== Features

* *pillar:* accept 'true'/True/true for booleans in pillars
(https://github.com/saltstack-formulas/exim-formula/commit/afe3e70[afe3e70^])
* *pillar:* some config values can be treated as lists
(https://github.com/saltstack-formulas/exim-formula/commit/481966d[481966d^])

== link:++https://github.com/saltstack-formulas/exim-formula/compare/v0.4.0...v0.5.0++[0.5.0^] (2019-10-05)

=== Code Refactoring

* *pillars:* extract default values to pillars
(https://github.com/saltstack-formulas/exim-formula/commit/72299cc[72299cc^])

=== Features

* *tofs:* add TOFS pattern
(https://github.com/saltstack-formulas/exim-formula/commit/7222790[7222790^])

== link:++https://github.com/saltstack-formulas/exim-formula/compare/v0.3.0...v0.4.0++[0.4.0^] (2019-10-04)

=== Bug Fixes

* *states:* add missing require sls
(https://github.com/saltstack-formulas/exim-formula/commit/726df07[726df07^])
* *states:* re-generate Exim aliases DB after update
(https://github.com/saltstack-formulas/exim-formula/commit/6a0aecf[6a0aecf^])

=== Continuous Integration

* *kitchen:* install required packages to bootstrapped `opensuse` [skip
ci]
(https://github.com/saltstack-formulas/exim-formula/commit/63a132e[63a132e^])
* *kitchen:* use bootstrapped `opensuse` images until `2019.2.2` [skip
ci]
(https://github.com/saltstack-formulas/exim-formula/commit/f1efdc9[f1efdc9^])
* *platform:* add `arch-base-latest` (commented out for now) [skip ci]
(https://github.com/saltstack-formulas/exim-formula/commit/89918b2[89918b2^])

=== Features

* *states:* add exim.mailname and exim.aliases states
(https://github.com/saltstack-formulas/exim-formula/commit/68bb801[68bb801^])

=== Performance Improvements

* *states:* reuse already fetched pillars
(https://github.com/saltstack-formulas/exim-formula/commit/c466c86[c466c86^])

=== Tests

* *inspec:* check that smtp port is opened
(https://github.com/saltstack-formulas/exim-formula/commit/a6418d3[a6418d3^])

== link:++https://github.com/saltstack-formulas/exim-formula/compare/v0.2.1...v0.3.0++[0.3.0^] (2019-09-25)

=== Features

* *map:* sync map.jinja with template-formula
(https://github.com/saltstack-formulas/exim-formula/commit/5ddd1c9[5ddd1c9^])

== link:++https://github.com/saltstack-formulas/exim-formula/compare/v0.2.0...v0.2.1++[0.2.1^] (2019-09-23)

=== Code Refactoring

* *states:* split exim metastate in .package/.config/.service
(https://github.com/saltstack-formulas/exim-formula/commit/a947ba9[a947ba9^])

=== Continuous Integration

* *kitchen:* change `log_level` to `debug` instead of `info`
(https://github.com/saltstack-formulas/exim-formula/commit/56d9573[56d9573^])

== link:++https://github.com/saltstack-formulas/exim-formula/compare/v0.1.0...v0.2.0++[0.2.0^] (2019-09-19)

=== Bug Fixes

* *inspec:* remove not supported platforms
(https://github.com/saltstack-formulas/exim-formula/commit/2e2de5e[2e2de5e^])

=== Continuous Integration

* *kitchen:* add Kitchen tests
(https://github.com/saltstack-formulas/exim-formula/commit/a5e936d[a5e936d^])
* *travis:* reduce test matrix
(https://github.com/saltstack-formulas/exim-formula/commit/a136c60[a136c60^])

=== Documentation

* *fix:* fix formula description
(https://github.com/saltstack-formulas/exim-formula/commit/04cb323[04cb323^])
* *pillar:* update link to Debian documentation
(https://github.com/saltstack-formulas/exim-formula/commit/2cd96e4[2cd96e4^])

=== Features

* *semantic-release:* add semantic-release
(https://github.com/saltstack-formulas/exim-formula/commit/d00a7bf[d00a7bf^])

=== Styles

* *yaml:* fix yaml linter warning
(https://github.com/saltstack-formulas/exim-formula/commit/3a219ab[3a219ab^])
